a=input("Enter a number: ")
b=input("Enter another number: ")
a=float(a)
b=float(b)
c=a+b
d=a-b
e=a*b
f=a/b
print("Addition =",c)
print("Subtraction =",d)
print("Multiplication =",e)
print("Division =",f)
